project_name: nodepanels-probe
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    id: "nodepanels-probe"
    binary: "nodepanels-probe-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    goos:
      - linux
      - windows
      #- freebsd
      #- openbsd
      #- netbsd
      #- dragonfly
      #- plan9
      #- solaris
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mips64le
      - mipsle
      #- ppc64
      - ppc64le
      - riscv64
      - s390x
archives:
  - format: binary